version: '3'
services:
    web:
        image: akash80e/tourist_app:webclient
        container_name: web
        network_mode: host
        ports:
            - "3000:5000"
            - "3000:5100"
        volumes:
            - ./web-client:/app
    search:
        image: akash80e/tourist_app:search_api
        container_name: search
        network_mode: host
        ports:
            - "5000:5000"
    ticket:
        image: akash80e/tourist_app:ticket_api
        container_name: ticket
        network_mode: host
        ports:
          - "5001:5001"
        volumes:
          - ./Backend/ticket:/app
